version: "3.7"

services:
    server:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 81:80
        networks:
            - app-network
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/

    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: Backpackcms
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql

    backpack:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - app-network
        volumes:
            - ./:/var/www

    node:
        image: node:15-alpine
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        command: sh /var/www/node_start.sh
        depends_on:
            - backpack

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
